# Generated by Django 3.0.1 on 2020-02-10 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resources/'),
            preserve_default=False,
        ),
    ]
