# Generated by Django 3.0.1 on 2020-02-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
